import { PANEL_TABS } from "../../editorView";

/**
 * The single source of user-facing copy for the prop editor and the prop bag.
 *
 * Every label, hint, tooltip and status message the editor or bag can show is
 * declared here, so the two surfaces read in one voice and a future translation
 * only has to touch this file. Dynamic copy lives in `MESSAGES` as small
 * functions; everything else is a frozen literal.
 *
 * Note: the `REFERENCE_TOOLTIPS` values are copied verbatim from the PalaceChat
 * client (including its American "color") because the task requires matching the
 * reference tooltip wording exactly. The rest of the client uses British
 * spellings ("colour", "favourite") for consistency with the existing UI.
 */

/** Exact PalaceChat tooltip wording for the editor's tools. Do not reword. */
export const REFERENCE_TOOLTIPS = {
  brush: "Brush tool (opaque stroke)",
  eraser: "Eraser tool (clears alpha)",
  fill: "Fill tool (flood fill)",
  pick: "Open color picker",
  clear: "Clear current frame to transparent",
  sampleKey: "Click a pixel to sample its color as the background to remove",
  exportWebp: "Export the current animation as a standalone .webp file",
  importOverlay: "Import external PNG/JPG/BMP/GIF/WebP as a draggable overlay",
} as const;

export const EDITOR = {
  title: "Prop Editor",
  dialogLabel: "Prop Editor",
  closeLabel: "Close the editor",
  menuLabel: "Editor menu",
  menus: { file: "File", edit: "Edit", image: "Image", view: "View", prop: "Prop ID" },
  file: {
    newCanvas: "New Canvas…",
    openImage: "Open Image…",
    openBagProp: "Open Bag Prop…",
    close: "Close",
  },
  edit: { undo: "Undo", redo: "Redo" },
  image: {
    addFrame: "Add Frame",
    duplicateFrame: "Duplicate Frame",
    deleteFrame: "Delete Frame",
  },
  view: {
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    actualSize: "Actual Size",
    fitWindow: "Fit to Window",
  },
  prop: {
    origin: "Origin",
    propId: "Prop ID",
    copyId: "Copy Prop ID",
    editId: "Edit ID & Name…",
    editIdHint: "Editing the prop id and name arrives with the save task",
  },
  working: "Working…",
  canvasHint: "Wheel to zoom · middle-drag to pan · drag on the Paint tab to paint",
  newBar: {
    label: "New canvas",
    width: "Width",
    height: "Height",
    create: "Create",
    cancel: "Cancel",
    maxHint: "Max 4096 per side",
  },
  zoom: {
    group: "Zoom",
    out: "Zoom out",
    in: "Zoom in",
    fit: "Fit",
    actualSize: "1:1",
    readout: "Zoom level",
  },
  frames: {
    group: "Frame navigation",
    previous: "Previous frame",
    next: "Next frame",
  },
  panels: { region: "Editor panels", tabs: "Panel tabs" },
  status: { tool: "Tool", prop: "Prop" },
  dismissError: "Dismiss the error",
  closeBagPicker: "Close the bag picker",
  confirmClose: {
    label: "Unsaved changes",
    text: "This document has unsaved changes. Close and discard them?",
    cancel: "Cancel",
    discard: "Discard & close",
  },
  shortcuts: {
    undo: "Ctrl+Z",
    redo: "Ctrl+Y",
    zoomIn: "Ctrl++",
    zoomOut: "Ctrl+-",
    actualSize: "Ctrl+1",
    fit: "Ctrl+0",
    save: "Ctrl+S",
    cyclePanel: "Alt+←/→",
  },
} as const;

/** Tooltips for editor controls beyond the reference tools. */
export const TOOLTIPS = {
  paint: { usePicked: "Use the picked colour" },
  transform: {
    flipHorizontal: "Flip the image horizontally",
    flipVertical: "Flip the image vertically",
    rotateCW: "Rotate 90° clockwise",
    rotateCCW: "Rotate 90° counter-clockwise",
    rotate180: "Rotate 180°",
    crop: "Crop to the rectangle above",
    cropSquare: "Crop to the largest centred square",
    shapeCrop: "Mask the image to the chosen shape",
  },
  adjust: {
    applyTone: "Apply brightness and contrast",
    resetTone: "Reset brightness and contrast to zero",
    applyColour: "Apply brightness, contrast and saturation",
    resetColour: "Reset the colour adjustment to zero",
    removeBackground: "Cut the keyed colour to transparent",
  },
  size: { resize: "Resize the whole document to the size above" },
  frames: {
    add: "Add a blank frame",
    duplicate: "Duplicate the current frame",
    delete: "Delete the current frame",
    moveUp: "Move the current frame earlier",
    moveDown: "Move the current frame later",
    copy: "Copy the current frame",
    paste: "Paste the copied frame",
    exportPng: "Export the current frame as PNG",
  },
  text: { addText: "Rasterize the text into a new layer" },
} as const;

export const CANVAS = {
  label: "Editor canvas",
  instructions:
    "Drag with the mouse to paint with the current tool. Pan with the middle mouse button or the arrow keys, zoom with plus and minus, and press 0 to fit.",
  frameAlt: "Current editor frame",
  emptyTitle: "No document open",
  emptyHint: "Use File to start a blank canvas, import an image, or open a bag prop.",
} as const;

export const PANELS = {
  header: {
    paint: "Paint",
    transform: "Transform",
    adjust: "Adjust",
    size: "Size",
    frames: "Frames",
    text: "Text",
    guides: "Guides",
    layers: "Layers",
  },
  common: {
    applyAllFrames: "Apply to all frames",
    noDocument: "No document open.",
  },
  paint: {
    colourBrush: "Colour & brush",
    tool: "Tool",
    colour: "Colour",
    brushColour: "Brush colour",
    usePicked: "Use",
    size: "Size",
    tolerance: "Fill tolerance",
    layer: "Layer",
    base: "Base",
    allFrames: "All frames",
    stroke: "Stroke (layer pixels)",
    fromX: "From X",
    fromY: "From Y",
    toX: "To X",
    toY: "To Y",
    brush: "Brush",
    eraser: "Eraser",
    fill: "Fill",
    pick: "Pick",
    clear: "Clear frame",
    note: "Drag on the canvas to paint with the current tool: Brush lays opaque colour, Eraser clears alpha. Typed coordinates still place one exact stroke, which is handy with a keyboard. Pick samples without changing the document.",
  },
  transform: {
    flipRotate: "Flip & rotate",
    flipH: "Flip H",
    flipV: "Flip V",
    rotateCW: "Rotate CW",
    rotateCCW: "Rotate CCW",
    rotate180: "Rotate 180",
    crop: "Crop",
    x: "X",
    y: "Y",
    width: "Width",
    height: "Height",
    cropButton: "Crop",
    squareCrop: "Square crop",
    shapeCrop: "Shape crop",
    shape: "Shape",
    square: "Square",
    circle: "Circle",
    rounded: "Rounded",
    radius: "Radius",
    zoom: "Zoom",
    rotation: "Rotation",
    resample: "Resample",
    bilinear: "Bilinear",
    nearest: "Nearest",
    applyShape: "Apply shape crop",
  },
  adjust: {
    tone: "Brightness / contrast",
    brightness: "Brightness",
    contrast: "Contrast",
    apply: "Apply",
    reset: "Reset",
    colour: "Colour",
    saturation: "Saturation",
    applyColour: "Apply colour",
    backgroundRemoval: "Background removal",
    key: "Key",
    keyColour: "Chroma key colour",
    sampleX: "Sample X",
    sampleY: "Sample Y",
    samplePixel: "Sample pixel",
    tolerance: "Tolerance",
    feather: "Feather",
    removeBackground: "Remove background",
  },
  size: {
    canvas: "Canvas",
    frames: "Frames",
    imageSize: "Image size",
    width: "Width",
    height: "Height",
    constrainAspect: "Constrain aspect",
    resample: "Resample",
    bilinear: "Bilinear (smooth)",
    nearest: "Nearest (pixel art)",
    presets: "Presets",
    resize: "Resize image",
    openDocument: "Open a document to resize it.",
  },
  frames: {
    add: "Add",
    duplicate: "Duplicate",
    delete: "Delete",
    moveUp: "Move up",
    moveDown: "Move down",
    copy: "Copy",
    paste: "Paste",
    saveToBag: "Save to bag",
    placement: "Placement",
    placements: {
      overwrite: "Overwrite in place",
      start: "New prop at start of bag",
      end: "New prop at end of bag",
    },
    name: "Name",
    namePlaceholder: "Default Prop Name",
    propId: "Prop ID",
    propIdPlaceholder: "auto",
    head: "Head",
    ghost: "Ghost",
    rare: "Rare",
    bounce: "Bounce",
    animate: "Animate",
    hOffset: "H offset",
    vOffset: "V offset",
    save: "Save to My Bag",
    export: "Export",
    exportPng: "Export PNG",
    exportWebp: "Export animation (WebP)",
    overwriteWarning:
      "Overwrite needs a prop opened from the bag; choose a new-prop placement instead.",
  },
  text: {
    textLayer: "Text layer",
    placeholder: "Type the words to draw",
    colour: "Colour",
    alpha: "Alpha",
    size: "Size",
    rotation: "Rotation",
    x: "X",
    y: "Y",
    opacity: "Opacity",
    shadow: "Drop shadow",
    outline: "Outline",
    wrap: "Wrap to width",
    addText: "Add text layer",
    overlay: "Overlay image",
    nameOptional: "Name (optional)",
    namePlaceholder: "Badge",
    importOverlay: "Import PNG / JPG / BMP / GIF / WebP",
    importOverlayHint: "Imported art becomes a new layer you can move, rotate, scale and fade.",
  },
  layers: {
    visibility: "Toggle visibility of",
    moveUp: "Move up",
    moveDown: "Move down",
    delete: "Delete layer",
    opacity: "Opacity",
    x: "X",
    y: "Y",
    rotation: "Rotation",
    scale: "Scale",
    positionNote: "Position is the layer's top-left corner, in canvas pixels.",
  },
  guides: {
    overlay: "Overlay",
    pixelGrid: "Pixel grid",
    centreGuides: "Centre guides",
    safeArea: "Safe area",
    thirds: "Rule of thirds",
    snapping: "Snapping",
    snapGrid: "Snap to grid",
    onionSkin: "Onion skin",
    onionPrevious: "Previous frame",
    onionNext: "Next frame",
    onionRadius: "Onion radius",
    note: "Guides are drawn over the frame only; they never change the pixels.",
    centreHint: "Centre guides draw the centre cross and snap placed points to the middle.",
    onionHint: "Ghosts the neighbouring frames so motion reads across the animation.",
  },
} as const;

export const BAG = {
  title: "Prop Bag",
  dialogLabel: "Prop Bag",
  closeLabel: "Close the prop bag",
  browserLabel: "Prop browser",
  loading: "Loading your bag…",
  loadFailed: "Your bag could not be loaded.",
  retry: "Try again",
  filters: {
    group: "Filter props",
    all: "All",
    favourites: "Favourites",
    trash: "Trash",
    searchPlaceholder: "Search name, id or crc",
    searchLabel: "Search props by name, id or crc",
    sort: "Sort",
    sortLabel: "Sort props",
    sortName: "Name",
    sortId: "ID",
    sortCollection: "Collection",
    indicators: "Indicators",
    resultCount: "Matching props",
    gridLabel: "Props",
  },
  trash: {
    holds: "Trash holds",
    empty: "Empty trash",
    confirm: "Confirm purge",
    cancel: "Cancel",
  },
  empty: {
    none: "No props in your bag yet.",
    noMatch: "Nothing matches this view.",
  },
  actions: {
    toolbar: "Prop actions",
    selected: "selected",
    newName: "New name",
    save: "Save",
    cancel: "Cancel",
    moveTo: "Move to",
    move: "Move",
    restore: "Restore",
    takeOff: "Take off",
    wear: "Wear",
    unfavourite: "Unfavourite",
    favourite: "Favourite",
    rename: "Rename",
    duplicate: "Duplicate",
    rebuildThumbnail: "Rebuild thumbnail",
    rebuildThumbnails: "Rebuild thumbnails",
    delete: "Delete",
    copyId: "Copy prop ID",
    clear: "Clear",
    takeAllOff: "Take all off",
    close: "Close",
    worn: "Worn",
    moveHintDisabled:
      "Moving needs a second writable collection; only My Bag is writable.",
    moveHint: "Move to another writable collection",
    trashHint: "Move to trash",
    trashHintDisabled: "Only props in My Bag can be trashed; shelves are read-only.",
    rebuildThumbnailHint: "Drop this prop's cached thumbnail and regenerate it",
    rebuildThumbnailsHint: "Drop every cached thumbnail; they regenerate as you browse",
  },
  sidebar: {
    region: "Bag collections and outfits",
    panel: "Bag panel",
    collections: "Collections",
    outfits: "Outfits",
    collectionsLabel: "Collections",
    all: "All collections",
    writable: "writable",
    none: "No bag collections found.",
  },
  outfits: {
    saveCurrent: "Save current outfit",
    nameLabel: "Outfit name",
    nameAria: "New outfit name",
    save: "Save",
    wearHint: "Wear at least one prop to save an outfit.",
    none: "No outfits saved yet.",
    apply: "Apply",
    rename: "Rename",
    delete: "Delete",
    ok: "OK",
    cancel: "Cancel rename",
    confirm: "Confirm?",
  },
  tile: {
    wear: "Wear",
    takeOff: "Take off",
    select: "Select",
    deselect: "Deselect",
  },
} as const;

/** Dynamic, user-facing copy. Keep pure so it can be unit-tested. */
export const MESSAGES = {
  /* Editor */
  copiedPropId: (id: number) => `Copied prop ID ${id}.`,
  clipboardUnavailable: (id: number) => `Prop ID ${id} (clipboard unavailable).`,
  rebuiltThumbnails: (count: number) =>
    count === 1 ? "Rebuilt 1 thumbnail." : `Rebuilt ${count} thumbnails.`,
  rebuiltThumbCache: (removed: number) =>
    removed === 1
      ? "Dropped 1 cached thumbnail; it regenerates as you browse."
      : `Dropped ${removed} cached thumbnails; they regenerate as you browse.`,
  painted: (size: number) => `Painted size-${size} stroke.`,
  erased: (size: number) => `Erased size-${size} stroke.`,
  floodFilled: "Flood-filled the region.",
  pickedColour: (hex: string) => `Picked ${hex}.`,
  noColour: "That pixel has no colour.",
  clearedFrame: "Cleared the frame to transparent.",
  flipped: (axis: string) => `Flipped ${axis}.`,
  rotated: (turn: string) => `Rotated ${turn}.`,
  cropped: "Cropped to the rectangle.",
  croppedSquare: "Cropped to the largest square.",
  shapeCropped: "Applied the shape crop.",
  appliedTone: "Applied brightness and contrast.",
  appliedColour: "Applied the colour adjustment.",
  sampledKey: (hex: string) => `Sampled key ${hex}.`,
  transparentPixel: "That pixel is transparent; nothing to sample.",
  removedBackground: "Removed the keyed background.",
  resized: (width: number, height: number) => `Resized to ${width} × ${height}.`,
  selectedFrame: (index: number) => `Selected frame ${index}.`,
  addedFrame: "Added a blank frame.",
  duplicatedFrame: "Duplicated the frame.",
  deletedFrame: "Deleted the frame.",
  movedFrameUp: "Moved the frame up.",
  movedFrameDown: "Moved the frame down.",
  copiedFrame: "Copied the frame.",
  pastedFrame: "Pasted the frame.",
  textAdded: "Text layer added.",
  textNeeded: "Type some text before adding a layer.",
  overlayAdded: (name: string) => `Overlay "${name}" added.`,
  layerUpdated: "Layer updated.",
  layerOpacity: "Opacity updated.",
  layerShown: "Shown.",
  layerHidden: "Hidden.",
  layerMovedUp: "Layer moved up.",
  layerMovedDown: "Layer moved down.",
  layerDeleted: "Layer deleted.",
  baseLayerProtected: "The base layer cannot be deleted.",
  exportedPng: "Exported the current frame as PNG.",
  exportedWebpAnimated: "Exported the current animation as a standalone .webp file.",
  exportedWebpFrame: "Exported the current frame as a standalone .webp file.",
  guideToggled: (label: string, on: boolean) => `${label} ${on ? "on" : "off"}.`,
  onionRadius: (radius: number) =>
    `Onion radius set to ${radius} frame${radius === 1 ? "" : "s"}.`,
  animatedSaveBlocked: (frames: number) =>
    `This document has ${frames} frames. Saving an animated prop is not supported yet; export the animation to WebP, or edit down to a single frame.`,
  bagLoadFailed: "The bag could not be loaded.",
  bagLoadFailedDetail: (cause: string) => `The bag could not be loaded: ${cause}`,

  /* Bag */
  propCount: (count: number) => `${count} prop(s)`,
  selectedCount: (count: number) => `${count} selected`,
  trashHolds: (count: number) => `Trash holds ${count} prop(s).`,
  confirmPurge: (count: number) => `Confirm purge (${count})`,
  wornCount: (worn: number, max: number) => `Worn ${worn} / ${max}`,
  copiedIntoBag: (count: number) => `Copied ${count} prop(s) into My Bag.`,
  nothingNewToCopy: "Nothing new to copy; already in My Bag.",
  noBagPath: (collection: string) => `No bag path is known for "${collection}".`,
  moveNeedsPaths: "Move needs two known collection paths.",
  couldNotWear: "That prop could not be worn.",
  thosePropsNotWorn: "Those props could not be worn.",
  outfitSaved: (name: string) => `Saved outfit "${name}".`,
  outfitApplied: (name: string) => `Applied "${name}".`,
  outfitFailed: "That outfit could not be applied.",
  purgedTrash: (count: number) => `Purged ${count} prop(s).`,
  collectionCount: (count: number) => `${count}`,
  showMore: (shown: number, total: number) => `Show more (${shown} / ${total})`,
  largeCollection: (count: number) => `Loaded ${count} props. Showing the first page; scroll for more.`,
} as const;

/** Keyboard hint text for controls that show their shortcut in a tooltip. */
export function withShortcut(label: string, shortcut: string): string {
  return `${label} (${shortcut})`;
}

/** Every panel label, in tab order — a convenience for accessible names. */
export const PANEL_LABELS = PANEL_TABS.map((tab) => PANELS.header[tab.id]);
